<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Zebra.Printer.Configurator.Core\Zebra.Printer.Configurator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Zebra.Printer.SDK" Version="5.0.3685" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>33</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
